// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA725ECsOg0p_pn9k4oGIpludbpTy31SqI',
    appId: '1:363998759689:web:2fc24b4bfd787de34621d8',
    messagingSenderId: '363998759689',
    projectId: 'skill-connect-7f2bb',
    authDomain: 'skill-connect-7f2bb.firebaseapp.com',
    storageBucket: 'skill-connect-7f2bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeekGtpEsfcKUIfPN0SkeN02DXm17LmWE',
    appId: '1:363998759689:android:ab717b61091cb0b44621d8',
    messagingSenderId: '363998759689',
    projectId: 'skill-connect-7f2bb',
    storageBucket: 'skill-connect-7f2bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkBkM1q7vhVI2PAku6HyA8sxANDu_h1e8',
    appId: '1:363998759689:ios:94d4a64b840ebd2b4621d8',
    messagingSenderId: '363998759689',
    projectId: 'skill-connect-7f2bb',
    storageBucket: 'skill-connect-7f2bb.firebasestorage.app',
    iosBundleId: 'com.example.skillconnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkBkM1q7vhVI2PAku6HyA8sxANDu_h1e8',
    appId: '1:363998759689:ios:94d4a64b840ebd2b4621d8',
    messagingSenderId: '363998759689',
    projectId: 'skill-connect-7f2bb',
    storageBucket: 'skill-connect-7f2bb.firebasestorage.app',
    iosBundleId: 'com.example.skillconnectApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA725ECsOg0p_pn9k4oGIpludbpTy31SqI',
    appId: '1:363998759689:web:088f2147b04be4b34621d8',
    messagingSenderId: '363998759689',
    projectId: 'skill-connect-7f2bb',
    authDomain: 'skill-connect-7f2bb.firebaseapp.com',
    storageBucket: 'skill-connect-7f2bb.firebasestorage.app',
  );
}
